spring:
  cloud:
    azure:
      storage:
        blob:
          endpoint: DefaultEndpointsProtocol=https;AccountName=storedineshvenba0811;AccountKey=***==;EndpointSuffix=core.windows.net
          account-name: storedineshvenba0811